doctrine_phpcr:
    session:
        default_session: ~
        sessions:
            eki_block:
                backend:
                    logging: true
                    profiling: true
                    type: doctrinedbal
                    connection: eki_block_connection
                    caches:
                        meta:  doctrine_cache.providers.phpcr_meta
                        nodes: doctrine_cache.providers.phpcr_nodes
                    parameters:
                        jackalope.disable_transactions: false
                        jackalope.check_login_on_server: false
                workspace: eki_block
                username: admin
                password: admin
                options: ~
    odm:
        locales:
            en_US: [vi_VN, fr_FR]
            vi_VN: [en_US, fr_FR]
            fr_FR: [en_US, vi_VN]
        locale_fallback: hardcoded
        default_document_manager: ~
        document_managers:
            eki_block:
                auto_mapping: true
                session: eki_block
