doctrine:
    dbal:
        connections:
            eki_block_connection:
                driver: pdo_mysql
                host: localhost
                user: ezpublish
                password: U6JXN5KfCwjJyoweSlSm
                dbname: ekiblock
                charset: UTF8
